services:
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.10'
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9300"
    #networks:
     # - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    #networks:
     # - elastic

volumes:
  elasticsearch-data:
  kibana-data:

#networks:
 # elastic:
  #  driver: bridge
